name: beauty_master
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  nb_utils: ^7.0.2
  intl: ^0.19.0

  # Common
  url_launcher: ^6.2.6
  http: ^1.2.1
  html: ^0.15.4

  # IMAGES & FONTS ICONS
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1

  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # MAP
  google_maps_flutter: ^2.6.1

  # UI
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  get_it: ^7.7.0

# dependency_overrides:
#   connectivity_plus: ^4.0.1
#   intl: ^0.17.0-nullsafety.2
#   http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter:
  uses-material-design: true

  assets:
    - fonts/
    - images/
